<?php
define('SENDSTUDIO_DATABASE_TYPE', 'mysql');
define('SENDSTUDIO_DATABASE_USER', 'iem_db_user');
define('SENDSTUDIO_DATABASE_PASS', 'cKK+8thgi!H2Ah+wp');
define('SENDSTUDIO_DATABASE_HOST', 'localhost:3306');
define('SENDSTUDIO_DATABASE_NAME', 'test');
define('SENDSTUDIO_DATABASE_UTF8PATCH', '1');
define('SENDSTUDIO_TABLEPREFIX', 'email_');
define('SENDSTUDIO_LICENSEKEY', 'IEM-ODMwYjc1N2M2MzM4MTUxM2NkZjMwZTEyMTA0ZGJhMTgtMWUyMzg1MjgyMGI5MTU0MzE2YzdjMDZlMmI3YmEwNTEtLXY8ODM1YTdhMGQ5MzIyYjViZT4tMC0wLTAtMwojOjA6MDowOjA6OTk5OjA6Njc5MmU2YTY=');
define('SENDSTUDIO_APPLICATION_URL', 'http://localhost:3001');
define('SENDSTUDIO_IS_SETUP', 1);
define('SENDSTUDIO_DEFAULTCHARSET', 'UTF-8');
